### PR TITLE
fix refetch + watchLoading when no new results are returned

### LINKED ISSUE #65: refetching a query breaks loadingKey if no new data is returned
at least i think that's what's causing it.

here's what happens: when i call `this.$apollo.queries.myQuery.refetch()` on a query with `loadingKey`, loading key gets increased but not decreased when the query finishes. i'm pretty sure that it happens when the data returned from my server has not changed. and i think it's because `next` is not called on the observer in this case. i'm not sure how to fix this, though. any pointer?

### PR DESCRIPTION
**Pull request by manukall**
fixes #65 
when the data hasn't changed, `nextResult` is not called and `loading` stays true. 
this resets loading in the promise returned from `refetch`.

### CODE REVIEW

File: src/smart-apollo.js [hunk 1]
```diff
@@ -264,7 +264,11 @@ export class SmartQuery extends SmartApollo {
   refetch (variables) {
     variables && (this.options.variables = variables)
     if (this.observer) {
-      const result = this.observer.refetch(variables)
+      const result = this.observer.refetch(variables).then((result) => {
+        if (result.loading === false) {
```
Comment (Akryum) [inline src/smart-apollo.js]: Please use `!result.loading` instead of `result.loading === false`.

**Comment by Akryum** [comment]
Thanks for your PR! :smile: I have left a comment in the changes that you should address before I merge this. :raised_hands:

**Comment by manukall** [comment]
@Akryum done :-)
